CREATE TABLE water_samples (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    aluminium REAL,
    ammonia REAL,
    arsenic REAL,
    barium REAL,
    cadmium REAL,
    chloramine REAL,
    chromium REAL,
    copper REAL,
    fluoride REAL,
    bacteria REAL,
    viruses REAL,
    lead REAL,
    nitrates REAL,
    nitrites REAL,
    mercury REAL,
    perchlorate REAL,
    radium REAL,
    selenium REAL,
    silver REAL,
    uranium REAL,
    is_safe BOOLEAN
);
